package com.example.application2

data class Formulaire(
    val id:Int,
    val nomsignaleur:String,
    val prenomsignaleur:String,
    val adrsignaleur:String,
    val telsignaleur:String,
    val signaleur:String,
    var prsnphysique:String,
    var sexeprsnphysique:String,
    var prsnmorale:String,
    var nomenfant:String,
    var prenomenfant:String,
    var sexeenfant:String,
    var ageenfant:Int?,
    var adrenfant:String,
    var cause:String,
    var description:String,
    var affichidentity:String,
    var dejasignaler:String,
    var nomerecevant:String,
    var prenomrecevant:String,
    var sexerecevant:String,
    var agerecevant:Int?,
    var adrrecevant:String,
    var situationfam:String,
    val replegal:String,
    var nomereplegal:String,
    var prenomreplegal:String,
    var sexereplegal:String,
    var agereplegal:Int?,
    var adrreplegal:String,
    var emploireplegal:String,
    val image:String,
    val son:String,
    val video:String,
    val etat :String
):java.io.Serializable
